### ISSUE TITLE
New instance after creating account fails at environments.single TRPC command

### ISSUE THREAD

**Issue by ajoslin** [interval/server#19]
I'm getting a failure after creating a new instance with a fresh account at /api/trpc/environments.single

```
GET /api/trpc/environments.single?batch=1&input=%7B%220%22%3A%7B%22json%22%3A%7B%22slug%22%3Anull%7D%2C%22meta%22%3A%7B%22values%22%3A%7B%22slug%22%3A%5B%22undefined%22%5D%7D%7D%7D%7D
```

It just returns a 400 over and over. The response payload is likeso:

```
[
    {
        "id": null,
        "error": "(function(a){return {message:a,code:-32600,data:{code:a,httpStatus:400,stack:\"TRPCError: BAD_REQUEST\\n    at Array.organizationMiddleware (\\u002Fusr\\u002Flocal\\u002Flib\\u002Fnode_modules\\u002F@interval\\u002Fserver\\u002Fdist\\u002Fsrc\\u002Fserver\\u002Ftrpc\\u002Futil.js:195:15)\\n    at callRecursive (\\u002Fusr\\u002Flocal\\u002Flib\\u002Fnode_modules\\u002F@interval\\u002Fserver\\u002Fnode_modules\\u002F@trpc\\u002Fserver\\u002Fdist\\u002Frouter-ee876044.cjs.dev.js:119:69)\\n    at next (\\u002Fusr\\u002Flocal\\u002Flib\\u002Fnode_modules\\u002F@interval\\u002Fserver\\u002Fnode_modules\\u002F@trpc\\u002Fserver\\u002Fdist\\u002Frouter-ee876044.cjs.dev.js:126:26)\\n    at Array.authenticatedMiddleware (\\u002Fusr\\u002Flocal\\u002Flib\\u002Fnode_modules\\u002F@interval\\u002Fserver\\u002Fdist\\u002Fsrc\\u002Fserver\\u002Ftrpc\\u002Futil.js:178:12)\\n    at callRecursive (\\u002Fusr\\u002Flocal\\u002Flib\\u002Fnode_modules\\u002F@interval\\u002Fserver\\u002Fnode_modules\\u002F@trpc\\u002Fserver\\u002Fdist\\u002Frouter-ee876044.cjs.dev.js:119:69)\\n    at Procedure.call (\\u002Fusr\\u002Flocal\\u002Flib\\u002Fnode_modules\\u002F@interval\\u002Fserver\\u002Fnode_modules\\u002F@trpc\\u002Fserver\\u002Fdist\\u002Frouter-ee876044.cjs.dev.js:144:26)\\n    at Router.call (\\u002Fusr\\u002Flocal\\u002Flib\\u002Fnode_modules\\u002F@interval\\u002Fserver\\u002Fnode_modules\\u002F@trpc\\u002Fserver\\u002Fdist\\u002Frouter-ee876044.cjs.dev.js:378:22)\\n    at Object.query (\\u002Fusr\\u002Flocal\\u002Flib\\u002Fnode_modules\\u002F@interval\\u002Fserver\\u002Fnode_modules\\u002F@trpc\\u002Fserver\\u002Fdist\\u002Frouter-ee876044.cjs.dev.js:384:21)\\n    at Object.callProcedure (\\u002Fusr\\u002Flocal\\u002Flib\\u002Fnode_modules\\u002F@interval\\u002Fserver\\u002Fnode_modules\\u002F@trpc\\u002Fserver\\u002Fdist\\u002FtransformTRPCResponse-36a41418.cjs.dev.js:12:19)\\n    at \\u002Fusr\\u002Flocal\\u002Flib\\u002Fnode_modules\\u002F@interval\\u002Fserver\\u002Fnode_modules\\u002F@trpc\\u002Fserver\\u002Fdist\\u002FresolveHTTPResponse-ab01e4b9.cjs.dev.js:205:52\\n    at Array.map (\\u003Canonymous\\u003E)\\n    at Object.resolveHTTPResponse (\\u002Fusr\\u002Flocal\\u002Flib\\u002Fnode_modules\\u002F@interval\\u002Fserver\\u002Fnode_modules\\u002F@trpc\\u002Fserver\\u002Fdist\\u002FresolveHTTPResponse-ab01e4b9.cjs.dev.js:201:48)\\n    at async Object.nodeHTTPRequestHandler (\\u002Fusr\\u002Flocal\\u002Flib\\u002Fnode_modules\\u002F@interval\\u002Fserver\\u002Fnode_modules\\u002F@trpc\\u002Fserver\\u002Fdist\\u002FnodeHTTPRequestHandler-9a93c255.cjs.dev.js:68:18)\\n    at async \\u002Fusr\\u002Flocal\\u002Flib\\u002Fnode_modules\\u002F@interval\\u002Fserver\\u002Fnode_modules\\u002F@trpc\\u002Fserver\\u002Fadapters\\u002Fexpress\\u002Fdist\\u002Ftrpc-server-adapters-express.cjs.dev.js:15:5\",path:\"environments.single\"}}}(\"BAD_REQUEST\"))"
    }
]
```

It's spitting some stacktrace into the response. Nothing in the logs on the server.

**Comment by theBeardA** [comment]
Any luck with this issue. I am facing exactly same issue

**Comment by heldrida** [comment]
If you look at the error message, the one above is very hard to read, but if you try to get the text terms, you find a call to `organizationMiddleware` and then `authenticatedMiddleware`. You know that the error message says `BAD_REQUEST`, which for the `organizationMiddleware` bit points to the source-code [here](https://github.com/interval/server/blob/77ae7f0f080f8530bec9f8d64b40f1f63524984a/src/server/trpc/util.ts#L224C1-L233C4):

```sh
// This relies on a header set by the client config if
// used within DashboardContext. Will not work elsewhere.
export const organizationMiddleware: MiddlewareFunction<
  AuthenticatedContext,
  OrganizationContext,
  unknown
> = ({ ctx, next }) => {
  if (!ctx.organizationId) {
    throw new trpc.TRPCError({ code: 'BAD_REQUEST' })
  }
  ...
```

Seem like missing environment variables and user fault?

**Comment by ajoslin** [comment]
Currently I'm setting APP_URL, DATABASE_URL, AUTH_COOKIE_SECRET, and WSS_API_SECRET only.

**Comment by austinjeane** [comment]
@ajoslin The issue is probably your reverse proxy setup. I had the same error, and it was due to the the cookies with underscores "_" being in the cookie names. NGINX for instance will strip all cookies with underscores as not valid. I had to add this to my NGINX config then it worked.

```
server {                                                                     
    server_name test.com;                                    
    underscores_in_headers on;                                               
                                                                             
    location / {                                                             
        proxy_pass_request_headers on;                                       
        proxy_pass http://localhost:3000;                                    
         ... rest of config here              
    }          
                                                              
      ... rest of config here                                                                   
}
```
